# Adapted from https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-docker.yml

name: CI (Coq, docker, dev)

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - env: { COQ_VERSION: "master", DOCKER_COQ_VERSION: "dev" }
          os: 'ubuntu-latest'

    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}
    name: ${{ matrix.env.COQ_VERSION }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.env.COQ_VERSION }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: all
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        custom_script: deps/coqutil/etc/ci/github-actions-docker-make.sh all
    - name: install
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        custom_script: sudo make install COQBIN="$(dirname "$(which coqc)")/"
    - name: display timing info
      run: cat time-of-build-pretty.log
    - name: display per-line timing info
      run: deps/coqutil/etc/ci/github-actions-display-per-line-timing.sh
