name: test1

on: [push]

jobs:
  updateBranch:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run some git commands
      run: |
        git branch -a
        git status
        git show HEAD --stat
        echo "$GITHUB_EVENT_PATH"
        cat "$GITHUB_EVENT_PATH"
